#python image from docker hub
FROM python:3.12-slim

# This sets the working directory inside the container to /app.
WORKDIR /app

#copy current directory contents into the container at /app
COPY . /app

# RUN pip install flask
COPY requirements.txt .
RUN pip install -r requirements.txt


EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "app.py"]